steps:
  - name: 'hashicorp/terraform'
    entrypoint: 'sh'
    args:
      - -c
      - |
        cd terraform
        terraform init
        terraform apply -auto-approve

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 900s